/** Paths for Top Navbar Items (Routes) */

const enum PATH_ENUMS {
    // Home and Root Nav Items
    HOME = "/",
    // Frontend
    FRONTEND_INDEX = "/frontend",
    FRONTEND_HTML = "/frontend/html",
    FRONTEND_CSS = "/frontend/css",
    FRONTEND_JS = "/frontend/js",
    FRONTEND_BOOTSTRAP = "/frontend/bs",
    FRONTEND_SASS = "/frontend/sass",
    FRONTEND_JEST = "/frontend/jest",
    FRONTEND_TS = "/frontend/ts",
    FRONTEND_VUE = "/frontend/vue",
    FRONTEND_VTU = "/frontend/vue-test-utils",
    FRONTEND_ANGULAR = "/frontend/angular",
    FRONTEND_WEBPACK = "/frontend/webpack",
    FRONTEND_VITE = "/frontend/vite",
    // Backend
    BACKEND_INDEX = "/backend",
    BACKEND_JAVA = "/backend/java",
    BACKEND_SPRING = "/backend/spring",
    BACKEND_HIBERNATE = "/backend/hibernate",
    BACKEND_JUNIT = "/backend/junit",
    BACKEND_CUCUMBER = "/backend/cucumber",
    BACKEND_OBJECT_MAPPER = "/backend/mapper",
    BACKEND_JSON = "/backend/json",
    BACKEND_XML = "/backend/xml",
    BACKEND_LOMBOK = "/backend/lombok",
    BACKEND_LOGGER = "/backend/logger",
    BACKEND_FEIGN = "/backend/feign",
    // APIs & Microservices
    API_INDEX = "/api",
    API_HTTP = "/api/http",
    API_CORS = "/api/cors",
    API_REST = "/api/rest",
    API_WEBSERVICES = "/api/webservices",
    API_MICROSERVICES = "/api/microservices",
    API_SWAGGER = "/api/swagger",
    API_OPENAPI = "/api/openapi",
    API_KAFKA = "/api/kafka",
    API_RABBIT_MQ = "/api/rabbit-mq",
    API_OWASP = "/api/owasp",
    // DevOps & CI/CD Tools
    DEVOPS_INDEX = "/devops",
    DEVOPS_GIT = "/devops/git",
    DEVOPS_GRADLE = "/devops/gradle",
    DEVOPS_JENKINS = "/devops/jenkins",
    DEVOPS_PUPPET = "/devops/puppet",
    DEVOPS_NGINX = "/devops/nginx",
    DEVOPS_CONTAINERIZATION = "/devops/containerization",
    DEVOPS_DOCKER = "/devops/docker",
    DEVOPS_KUBERNETES = "/devops/kubernetes",
    DEVOPS_NOMAD = "/devops/nomad",
    DEVOPS_ELK = "/devops/elk",
    DEVOPS_GRAFANA = "/devops/grafana",
    // SWE
    SWE_INDEX = "/swe",
    SWE_CLEAN_CODE = "/swe/clean-code",
    SWE_DESIGN_PATTERNS = "/swe/design-patterns",
    SWE_CLOUD_COMPUTING = "/swe/cloud-computing",
    SWE_DISTRIBUTED_SYSTEMS = "/swe/distributed-systems",
    SWE_SYSTEM_DESIGN = "/swe/system-design",
    SWE_SYSTEM_DESIGN_EXAMPLES = "/swe/system-design-examples",
    SWE_AWS = "/swe/aws",
    // CSE Core
    CSE_INDEX = "/cse",
    CSE_DS = "/cse/ds",
    CSE_ALGO = "/cse/algo",
    CSE_OS = "/cse/os",
    CSE_DBMS = "/cse/dbms",
    CSE_CN = "/cse/networks",
    CSE_PROG_BASIC = "/cse/programming-basics",
    CSE_CHEATSHEET = "/cse/cheatsheet",
    CSE_PUZZLES = "/cse/puzzles",
    // Miscellaneous
    AI_INDEX = "/ai",
    AI_INTRO = "/ai/intro",
    // Miscellaneous
    MISC_INDEX = "/misc",
    MISC_REFS = "/misc/refs",
    MISC_API_EXAMPLES = "/misc/api-examples",
    MISC_MARKDOWN_EXAMPLES = '/misc/markdown-examples',
    MISC_JEKYLL = "/misc/jekyll",
    MISC_CHROME = "/misc/chrome",
}

export default PATH_ENUMS;
