import { default as PATHS } from "./paths.ts";
import { DefaultTheme } from "vitepress";
import * as SIDEBARS from './sidebars/index.ts';

/** Custom Sidebar for URL */
const ALL_SIDEBARS:DefaultTheme.SidebarMulti = {
    // Tracks
    [PATHS.FRONTEND_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,    
    [PATHS.BACKEND_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.DEVOPS_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    // Interview
    [PATHS.INTERVIEW_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_INTERVIEW,
    [PATHS.INTERVIEW_CODING]: SIDEBARS.SIDEBAR_INTERVIEW_CODING,
    [PATHS.INTERVIEW_LLD]: SIDEBARS.SIDEBAR_INTERVIEW_LLD,
    [PATHS.INTERVIEW_SYSTEM_DESIGN]: SIDEBARS.SIDEBAR_INTERVIEW_SYSTEM_DESIGN,
    [PATHS.INTERVIEW_CONCURRENCY]: SIDEBARS.SIDEBAR_INTERVIEW_CONCURRENCY,
    // AI
    [PATHS.AI_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_AI,
    // Misc
    [PATHS.MISC_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
    // DEFAULT for site
    [PATHS.HOME]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
}

export default ALL_SIDEBARS;