import { default as PATHS } from "./paths.ts";
import { DefaultTheme } from "vitepress";
import * as SIDEBARS from './sidebars/index.ts';

/** Custom Sidebar for URL */
const ALL_SIDEBARS:DefaultTheme.SidebarMulti = {
    // Tracks
    [PATHS.FRONTEND_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.DEVOPS_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.BACKEND_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_JAVA]: SIDEBARS.SIDEBAR_BACKEND_JAVA,
    [PATHS.BACKEND_SPRING]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    // Interview
    [PATHS.INTERVIEW_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_INTERVIEW,
    [PATHS.INTERVIEW_CODING]: SIDEBARS.SIDEBAR_INTERVIEW_CODING,
    [PATHS.INTERVIEW_LLD]: SIDEBARS.SIDEBAR_INTERVIEW_LLD,
    [PATHS.SYSTEM_DESIGN_INDEX]: SIDEBARS.SIDEBAR_SYSTEM_DESIGN_INTERVIEW,
    [PATHS.SYSTEM_DESIGN_CONCEPTS]: SIDEBARS.SIDEBAR_SYSTEM_DESIGN_CONCEPTS,
    [PATHS.SYSTEM_DESIGN_INTERVIEW]: SIDEBARS.SIDEBAR_SYSTEM_DESIGN_INTERVIEW,
    [PATHS.INTERVIEW_CONCURRENCY]: SIDEBARS.SIDEBAR_INTERVIEW_CONCURRENCY,
    // AI
    [PATHS.AI_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_AI,
    // Misc
    [PATHS.MISC_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
    // DEFAULT for site
    [PATHS.HOME]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
}

export default ALL_SIDEBARS;