import { default as PATHS } from "./paths";
import { DefaultTheme } from "vitepress";
import * as SIDEBARS from './sidebars/index.ts';

/** Custom Sidebar for URL */
const ALL_SIDEBARS:DefaultTheme.SidebarMulti = {
    // Frontend
    [PATHS.FRONTEND_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    // Backend
    [PATHS.BACKEND_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_JAVA]: SIDEBARS.SIDEBAR_JAVA,
    [PATHS.BACKEND_SPRING]: SIDEBARS.SIDEBAR_SPRING,
    // APIs
    [PATHS.API_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_API,
    // Devops & CICD
    [PATHS.DEVOPS_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    // SWE
    [PATHS.SWE_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_SWE,
    // CSE
    [PATHS.CSE_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_CSE,
    // AI
    [PATHS.AI_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_AI,
    // Misc
    [PATHS.MISC_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
    // HOME
    [PATHS.UTILS]: SIDEBARS.SIDEBAR_DEFAULT_UTILS,
    [PATHS.HOME]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
}

export default ALL_SIDEBARS;