import { default as PATHS } from "./paths.ts";
import { DefaultTheme } from "vitepress";
import * as SIDEBARS from './sidebars/index.ts';

/** Custom Sidebar for URL */
const ALL_SIDEBARS:DefaultTheme.SidebarMulti = {
    // Tracks
    [PATHS.FRONTEND_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,    
    [PATHS.BACKEND_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.DEVOPS_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    // Interview
    [PATHS.INTERVIEW_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_INTERVIEW,
    [PATHS.INTERVIEW_CODING]: SIDEBARS.SIDEBAR_INTERVIEW_CODING,
    // APIs
    [PATHS.API_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_API,
    // SWE
    [PATHS.SWE_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_SWE,
    // AI
    [PATHS.AI_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_AI,
    // Misc
    [PATHS.MISC_INDEX]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
    // HOME
    [PATHS.HOME]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
}

export default ALL_SIDEBARS;