http {
    
    # types {
    #     text/html html;
    #     text/css css;
    # }
    include mime.types;

    upstream backendserver {
        server 127.0.0.1:1111;
        server 127.0.0.1:1112;
        server 127.0.0.1:1113;
        server 127.0.0.1:1114;
    }

    server {
        listen 8080;
        root ./devops/nginx/mysite;
        location / {
            proxy_pass http://backendserver/;
            # default round robin load balancing method
        }
        location /fruits {
            root ./devops/nginx/mysite;
        }
        location /carbs {
            alias ./devops/nginx/mysite;
        }
        location /vegetables {
            root ./devops/nginx/mysite;
            try_files /veggies.html /index.html =404;
        }
        location ~* /count/[0-9] {
            root ./devops/nginx/mysite;
            try_files /count.html /index.html =404;
        }
        # Redirect
        location /crops {
            return 307 /fruits;
        }
        # Rewrite
        rewrite ^/number/(\w+)$ /count/$1 break;
    }
}

events {

}